version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  pre_build:
    commands:
      - echo "Installing Composer..."
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - echo "Installing dependencies..."
      - composer install
  build:
    commands:
      - echo "Building project..."
      - npm install

artifacts:
  files:
    - "**/*"
  name: app-$(date +%Y-%m-%dT%H:%M:%S).zip

cache:
  paths:
    - '/root/.composer/cache'

proxy:
  upload-artifacts: yes
  logs: yes